apiVersion: v1
kind: Secret
metadata:
  name: forms-postgresql
  namespace: default
  labels:
    app: forms-postgresql
type: Opaque
data:
  postgresql-password: OGY4YzQ3NGUzMmI1OGQ0NjQ4MjBhMWRiZGJlMGEyMTY3ZThmNWJjMDMzMTkwN2I4ODBhMDBiNjY5NTVk
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: forms-postgresql
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: forms-postgresql
  template:
    metadata:
      labels:
        app: forms-postgresql
    spec:
      volumes:
        - name: data
          emptyDir: {}
      containers:
        - name: postgres
          image: postgres:12.3
          env:
            - name: POSTGRES_USER
              value: forms
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: forms-postgresql
                  key: postgresql-password
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql/data
              subPath: postgres
          resources:
            requests:
              memory: '512Mi'
              cpu: '500m'
            limits:
              memory: '1Gi'
              cpu: '1'
---
apiVersion: v1
kind: Service
metadata:
  name: forms-postgresql
  namespace: default
spec:
  selector:
    app: forms-postgresql
  ports:
    - port: 5432
